language: java

jdk:
  - oraclejdk8

script: mvn clean install coveralls:report

branches:
  only: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/

notifications:
  email: true
